In [1]:
import pandas as pd
import numpy as np

In [2]:
df_WB = pd.read_excel("/Users/abhishek/Desktop/World_bank_indicators _analytics/WDIEXCEL.xlsx")

In [4]:
df_WB.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.998179,35.240236,36.080572,NaN

In [8]:
df_WB.shape

(396970, 70)

In [9]:
df_WB.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025'],
      dtype='object')

In [10]:
WB_copy = df_WB

In [11]:
WB_copy.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.998179,35.240236,36.080572,NaN

In [14]:
df_new = WB_copy.dropna() # drop the rows with atleast one element missing

In [22]:
df_WB.isna().sum()#Indicate missing values.

Country Name           0
Country Code           0
Indicator Name         0
Indicator Code         0
1960              359744
                   ...
2021              185497
2022              198974
2023              212798
2024              246812
2025              315299
Length: 70, dtype: int64

In [21]:
  WB_copy.isnull().sum()

Country Name           0
Country Code           0
Indicator Name         0
Indicator Code         0
1960              359744
                   ...
2021              185497
2022              198974
2023              212798
2024              246812
2025              315299
Length: 70, dtype: int64

In [17]:
len(df_new)

24314

In [18]:
len(WB_copy)

396970

In [37]:
# Task 1: Find out how many distinct sheets exist in the Excel workbook and inspect their labels.
WB_excel = pd.ExcelFile("/Users/abhishek/Desktop/World_bank_indicators _analytics/WDIEXCEL.xlsx")
sheet_names = WB_excel.sheet_names
print(sheet_names)
# Task 2: Load the specific metadata sheet that contains indicator definitions and topics into a DataFrame.
df_indicator = pd.read_excel(WB_excel, sheet_name ='Series')
print(df_indicator.head())
# Task 3: Group or count the indicators by their broad development topic to see the distribution.
#Group by in the pandass yehhh--> okay broo 
df_indicator.groupby('Topic')['Indicator Name'].count()

['Data', 'Country', 'Series', 'country-series', 'series-time', 'footnote']
         Series Code                                 Topic  \
0  AG.CON.FERT.PT.ZS  Environment: Agricultural production
1     AG.CON.FERT.ZS  Environment: Agricultural production
2     AG.LND.AGRI.K2                 Environment: Land use
3     AG.LND.AGRI.ZS                 Environment: Land use
4     AG.LND.ARBL.HA                 Environment: Land use

                                      Indicator Name  Short definition  \
0  Fertilizer consumption (% of fertilizer produc...               NaN
1  Fertilizer consumption (kilograms per hectare ...               NaN
2                         Agricultural land (sq. km)               NaN
3                 Agricultural land (% of land area)               NaN
4                             Arable land (hectares)               NaN

                                     Long definition  \
0  Fertilizer consumption measures the quantity o...
1  Fertilizer consumption measures the quantity o...
2  Agricultural land refers to the land area that...
3  Agricultural land refers to the share of land ...
4  Arable land (in hectares) includes land define...

                 Unit of measure Periodicity  Base Period  \
0                      % (ratio)      Annual          NaN
1  kg per hectare of arable land      Annual          NaN
2     square kilometers (sq. km)      Annual          NaN
3         % (share) of land area      Annual          NaN
4                       hectares      Annual          NaN

                                         Other notes Aggregation method  \
0  The world and regional aggregate series do not...   Weighted average
1  The world and regional aggregate series do not...   Weighted average
2  Areas of former states are included in the suc...                Sum
3  Areas of former states are included in the suc...   Weighted average
4  Areas of former states are included in the suc...                NaN

                          Limitations and exceptions  \
0  The FAO has revised the time series for fertil...
1  The FAO has revised the time series for fertil...
2  The data are collected by the Food and Agricul...
3  The data are collected by the Food and Agricul...
4  The Food and Agriculture Organization (FAO) tr...

   Notes from original source  General comments  \
0                         NaN               NaN
1                         NaN               NaN
2                         NaN               NaN
3                         NaN               NaN
4                         NaN               NaN

                                              Source  \
0  FAO electronic files and web site, Food and Ag...
1  FAO electronic files and web site, Food and Ag...
2  FAO electronic files and web site, Food and Ag...
3  FAO electronic files and web site, Food and Ag...
4  FAO electronic files and web site, Food and Ag...

                 Statistical concept and methodology  \
0  Methodology: Fertilizer consumption measures t...
1  Methodology: Fertilizer consumption measures t...
2  Methodology: Agricultural land constitutes onl...
3  Methodology: Agriculture is still a major sect...
4  Methodology: Temporary fallow land refers to l...

                               Development relevance  Related source links  \
0  Factors, such as the green revolution, have le...                   NaN
1  Factors, such as the green revolution, have le...                   NaN
2  Agricultural land covers more than one-third o...                   NaN
3  Agricultural land covers more than one-third o...                   NaN
4  Agricultural land covers more than one-third o...                   NaN

   Other web links  Related indicators License Type
0              NaN                 NaN    CC BY-4.0
1              NaN                 NaN    CC BY-4.0
2              NaN                 NaN    CC BY-4.0
3              NaN                 NaN    CC BY-4.0
4              NaN                 NaN    CC BY-4.0

Topic
Economic Policy & Debt: Balance of payments: Capital & financial account                  11
Economic Policy & Debt: Balance of payments: Current account: Balances                     4
Economic Policy & Debt: Balance of payments: Current account: Goods, services & income    22
Economic Policy & Debt: Balance of payments: Current account: Transfers                    7
Economic Policy & Debt: Balance of payments: Reserves & other items                        6
                                                                                          ..
Social Protection & Labor: Labor force structure                                          28
Social Protection & Labor: Migration                                                      13
Social Protection & Labor: Performance                                                    27
Social Protection & Labor: Unemployment                                                   27
Trade                                                                                     24
Name: Indicator Name, Length: 93, dtype: int64